# Generated by Django 5.0 on 2024-01-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_alter_car_owner_alter_moto_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=9, verbose_name='Цена'),
        ),
    ]
