# Generated by Django 4.2.9 on 2024-01-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_car_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milage',
            options={'ordering': ('-year',), 'verbose_name': 'Пробег', 'verbose_name_plural': 'Пробеги'},
        ),
        migrations.AddField(
            model_name='moto',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=12, verbose_name='Цена'),
        ),
    ]
